Algoritmo "EXERCICIO_Z"
// Disciplina   : Algoritmo
// Descrição   : Programa que calcula o quadrado da divisão de dois valores inteiros
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 26/10/2022
Var

   A, B : inteiro
   RESULTADO : real

Inicio

      escreva("Digite o valor inteiro de A: ")
      leia(A)
      escreva("Digite o valor inteiro de B: ")
      leia(B)
      RESULTADO <- Exp(A div B, 2)
      escreval("O quadrado da divisão de", A, " e", B, " é", RESULTADO)

Fimalgoritmo