Algoritmo "EXERCICIO_X"
// Disciplina   : Algoritmo
// Descrição   : Programa que calcula a raiz
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 26/10/2022
Var

   RAIZ, BASE, INDICE : real

Inicio

      escreva("Digite a base númerica: ")
      leia(BASE)
      escreva("Digite o índice númerico: ")
      leia(INDICE)
      RAIZ <- Exp(BASE, 1/INDICE)
      escreval("A raiz equivale a", RAIZ:6:2)

Fimalgoritmo