Algoritmo "EXERCICIO_B"
// Disciplina   : Algoritmos
// Descrição   : Algoritmo que recebe dados em Celisius e os converte para Fahrenheit
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 25/10/2022
Var

   F, C : real

Inicio

      escreva("Digite o graus em Fahrenheit: ")
      leia(F)
      C <- ((F - 32) * 5) / 9
      escreva("Os graus convertidos em Celsius: ", C, "ºC")
      
Fimalgoritmo