Algoritmo "EXERCICIO_J"
// Disciplina   : Algoritmo
// Descrição   : Programa que recebe um valor inteiro e exibe se é par ou ímpar.
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 31/10/2022
Var

   VALOR : inteiro

Inicio

      escreva("Digite um valor inteiro: ")
      leia(VALOR)
      
      se (VALOR mod 2 = 0) entao
         escreval("O valor", VALOR, " é par.")
      senao
         escreval("O valor", VALOR, " é ímpar.")
      fimse

Fimalgoritmo