Algoritmo "EXERCICIO_T"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/11/2022
Var

   CONTADOR : inteiro

Inicio

      para CONTADOR de 15 ate 200 passo 3 faca
             escreval("O número ", CONTADOR, " elevado a quadrado é", Exp(CONTADOR, 2))
      fimpara

Fimalgoritmo