Algoritmo "EXERCICIO_A"
// Disciplina   : Algoritmo
// Descrição   : Programa que calcula o quadrado de 15 até 200.
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 04/11/2022
Var

   VALOR_QUADRADO : real
   CONTADOR : inteiro

Inicio

      para CONTADOR de 15 ate 200 faca
         escreva("O valor ", CONTADOR, " ao quadrado é")
         VALOR_QUADRADO <- Exp(CONTADOR, 2)
         escreva(VALOR_QUADRADO)
         escreval
      fimpara

Fimalgoritmo