Algoritmo "EXERCICIO_T"
// Disciplina   : Algoritmo
// Descrição   : Programa que calcula os valores ao quadrado, da faixa de 15 a 200, pulando de 3 em 3.
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 07/11/2022
Var

   CONTADOR : inteiro

Inicio

      para CONTADOR de 15 ate 200 passo 3 faca
             escreval("O número ", CONTADOR, " elevado a quadrado é", Exp(CONTADOR, 2))
      fimpara

Fimalgoritmo