Algoritmo "EXERCICIO_J"
// Disciplina   : Algoritmo
// Descrição   : Programa que lê temperatura em Celsius converte para Fahrenheit e exibe os dois valores.
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 07/11/2022
Var

   C, F : real

Inicio

   C <- 10

   enquanto (C <= 100) faca
      F <- C * 9/5 + 32
      escreval("A temperatura de", C, " ºC convetido em Fahrenheit é ", F, " ºF.")
      C <- C + 10
   fimenquanto

Fimalgoritmo