Algoritmo "LACO_POS_TESTE_VERDADEIRO_VA"
// Disciplina   : Algoritmo
// Descrição   : Exemplo de laço condioional verdadeiro iterativo
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 03/11/2022
Var

   I, N, R : inteiro

Inicio

      I <- 1
      
      repita

         escreva("Digite um valor inteiro qualquer: ")
         leia(N)

         R <- N * 3

         escreval(N, " x 3 =", R)

         I <- I + 1

      ate (I >= 5)

Fimalgoritmo