Algoritmo "LACO_INCONDICIONAL"
// Disciplina   : Algoritmo
// Descrição   : Exemplo de laço incondicional
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 03/11/2022
Var

   I, N, R : inteiro

Inicio

      para I de 1 ate 5 passo 1 faca
         escreva("Digite um valor inteiro qualquer: ")
         leia(N)

         R <- N * 3

         escreval(N, " x 3 =", R)
      fimpara

Fimalgoritmo