Algoritmo "NOME_SEXO"
// Disciplina   : Algoritmo
// Descrição   : Programa que solicita o nome e o sexo e os apresenta
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 25/10/2022
Var

   NOME : caractere
   SEXO : caracter

Inicio

      escreva("Digite o nome: ")
      leia(NOME)
      escreva("Digite o sexo (M/F): ")
      leia(SEXO)
      
      escreval("Nome: ", NOME)
      escreva("Sexo: ", SEXO)

Fimalgoritmo