Algoritmo "soma_numeros"
// Livro: Algoritmos
// Descrição   : O programa lê dois valores inteiro positivos e os soma
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 25/10/2022
Var

   X : inteiro
   A : inteiro
   B : inteiro

Inicio
      escreva("Digite o valor de A: ")
      leia(A)
      escreva("Digite o valor de B: ")
      leia(B)
      X <- A + B
      escreva("O valor de X é")
      escreva(X)

Fimalgoritmo