Algoritmo "LACO_POS_TESTE_FALSO_VA"
// Disciplina   : Algoritmo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/11/2022
Var

   I, N, R : inteiro

Inicio

      I <- 1
      
      repita

         escreva("Digite um valor inteiro qualquer: ")
         leia(N)

         R <- N * 3

         escreval(N, " x 3=", R)
      
      ate (I > 5)

Fimalgoritmo