Algoritmo "EXERCICIO_Y"
// Disciplina   : Algoritmo
// Descrição   : Programa que lê um valor inteiro e devolve seu sucessor e antecessor
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 26/10/2022
Var

   NUMERO, ANTECESSOR, SUCESSOR : inteiro

Inicio

      escreva("Digite um valor númerico inteiro: ")
      leia(NUMERO)
      ANTECESSOR <- NUMERO - 1
      SUCESSOR <- NUMERO + 1
      escreval("Sucessor = ", SUCESSOR)
      escreval("Antecessor = ", ANTECESSOR)

Fimalgoritmo