Algoritmo "EXERCICIO_W"
// Disciplina   : Algoritmo
// Descrição   : Programa que recebe uma medida em pés e devolve em metros
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 26/10/2022
Var

   PES, METROS : real

Inicio

      escreva("Digite o valor (cm) da medida em pés desejada: ")
      leia(PES)
      METROS <- PES * 0.3048
      escreva("O valor de ", PES:6:2, " pés convertido em metros é ", METROS:2:2, " m.")

Fimalgoritmo