Algoritmo "EXERCICIO_F"
// Disciplina   : Algoritmos
// Descrição   : Programa que lê A e B e efetua a troca de valores
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 25/10/2022
Var

   A, B, TROCA : inteiro

Inicio

      escreva("Digite o valor de A: ")
      leia(A)
      escreva("Digite o valor de B: ")
      leia(B)
      TROCA <- A
      A <- B
      B <- TROCA
      escreval("A =", A)
      escreva("B =", B)

Fimalgoritmo