Algoritmo "EXERCICIO_J"
// Disciplina   : Algoritmos
// Descrição   : Programa que calcula o quadrado da diferença entre A e B
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 26/10/2022
Var

   A, B, RESULTADO : inteiro

Inicio

      escreva("Digite o valor de A: ")
      leia(A)
      escreva("Digite o valor de B: ")
      leia(B)
      RESULTADO <- A * A - B * B
      escreva("O quadrado da diferença é", RESULTADO)

Fimalgoritmo