Algoritmo "EXERCICIO_C"
// Disciplina   : Algoritmos
// Descrição   : Algoritmo que calcula o volume de uma lata de óleo
// Autor(a)    : Lucas Pereira de Lima
// Data atual  : 25/10/2022
Var

   R, ALTURA, VOLUME : real

Inicio

      escreva("Digite o valor do raio de lata de óleo: ")
      leia(R)
      escreva("Digite a altura da lata de óleo: ")
      leia(ALTURA)
      VOLUME <- 3.14159 * Exp(R, 2) * ALTURA
      escreva("O valor do volume da lata de óleo é ", VOLUME)

Fimalgoritmo